<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TwinShop.DAL\TwinShop.DAL.csproj" />
    <ProjectReference Include="..\TwinShop.Shared\TwinShop.Shared.csproj" />
  </ItemGroup>

</Project>
